defaults:
  - base_environment


output_dir: /media/osterburg/bd8c1d08-1525-441a-bc14-23884138fa74/Logging/
dataset_root: /media/osterburg/ec7ca372-d0b6-42e8-a36b-8a14e8cda8e5/Datasets/KISSaF/
batch_size: 512

num_workers: 5

wandb:
  entity: timo-osterburg
  project: HiLO