name: LegacyMatchingLoss

loss_weights:
  ce: 3.3726949364267744
  bbox: 0.1
  giou: 9.401898369085808
  motion: 2.491881744896565

match_weights:
  ce: 2.6465544504238774
  bbox: 0.1
  giou: 9.2199440622492

number_of_classes: ${data.number_of_classes}

class_weight_computation:
  normalization: ENS
  beta: 0.9999
  class_counts: ${data.class_counts}

class_weights: ${data.class_weights}

number_of_queries: ${model.number_of_predictions}
num_samples: ${data.num_samples}